-- MoodTrip seed data (tergenerate dari lib/ oleh scripts/generate-seed.ts)
-- Jalankan SETELAH schema.sql.

-- Tags
insert into public.tags (name, kind) values
  ('landmark', 'mood'),
  ('aesthetic', 'mood'),
  ('budaya', 'mood'),
  ('keluarga', 'mood'),
  ('murah', 'mood'),
  ('foto-foto', 'mood'),
  ('healing', 'mood'),
  ('tenang', 'mood'),
  ('jalan santai', 'mood'),
  ('kota', 'mood'),
  ('sunset', 'mood'),
  ('romantis', 'mood'),
  ('pantai', 'mood'),
  ('populer', 'mood'),
  ('adventurous', 'mood'),
  ('nature', 'mood'),
  ('lokal banget', 'mood'),
  ('belajar budaya', 'mood'),
  ('hidden gem', 'mood'),
  ('pedas', 'mood'),
  ('kuliner lokal', 'mood'),
  ('halal', 'mood'),
  ('food hunter', 'mood'),
  ('malam', 'mood'),
  ('cepat', 'mood'),
  ('cozy', 'mood'),
  ('nongkrong', 'mood'),
  ('snorkeling', 'mood'),
  ('air terjun', 'mood'),
  ('Beach Junkie', 'minat'),
  ('Foodie Enthusiast', 'minat'),
  ('Adrenaline Junkie', 'minat'),
  ('Sunset Chaser', 'minat'),
  ('Hidden Gem Hunter', 'minat'),
  ('Culture Buff', 'minat'),
  ('Coffee Addict', 'minat'),
  ('Photo Enthusiast', 'minat'),
  ('Budget Traveler', 'minat'),
  ('Healing Seeker', 'minat'),
  ('Night Owl', 'minat'),
  ('Family Tripper', 'minat')
on conflict (name) do nothing;

-- Spots
insert into public.spots (id, name, category, location, description, uniqueness, price_min, price_label, hours, rating, lat, lng, gallery, fasilitas) values
  (1, 'Islamic Center NTB', 'Landmark Kota', 'Mataram', 'Landmark ikonik Mataram dengan area luas dan arsitektur megah.', 'Cocok untuk wisata religi, foto arsitektur, dan mengenal identitas kota.', 0, 'Gratis', '08.00 - 21.00', 4.7, -8.5838, 116.1178, array['/images/Islamic_center_ntb.jpg', 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=70', 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir luas', 'Toilet', 'Musala', 'Area foto', 'Ramah difabel']::text[]),
  (2, 'Taman Sangkareang', 'Ruang Publik', 'Pusat Kota Mataram', 'Taman kota untuk jalan santai, olahraga ringan, dan berkumpul sore hari.', 'Tempat murah dan mudah dijangkau untuk healing singkat di tengah kota.', 0, 'Gratis', '05.30 - 22.00', 4.3, -8.5852, 116.1119, array['/images/Sangkareang.jpg', 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=70', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=70']::text[], array['Gratis masuk', 'Jogging track', 'Playground', 'Kursi taman', 'PKL sekitar']::text[]),
  (3, 'Pantai Senggigi', 'Wisata Pantai', 'Lombok Barat', 'Pantai populer dengan garis pantai panjang, sunset, dan pilihan kuliner sekitar.', 'Spot sunset klasik Lombok yang cocok untuk pasangan dan keluarga.', 10000, 'Rp10.000 - Rp30.000', '06.00 - 19.00', 4.6, -8.4923, 116.0429, array['/images/pantai_senggigi.jpg', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=70', 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Warung & kafe', 'Sewa kano', 'Toilet & bilas', 'Spot sunset']::text[]),
  (4, 'Bukit Merese', 'Wisata Alam', 'Kuta Lombok', 'Bukit savana dengan pemandangan laut dan jalur naik yang relatif ringan.', 'View luas untuk healing, foto, dan menikmati angin pantai.', 10000, 'Rp10.000 - Rp25.000', '05.30 - 18.30', 4.8, -8.9012, 116.3078, array['/images/merese.jpeg', '/images/trek_merese.jpg', 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir bawah bukit', 'Warung kecil', 'Jalur trekking ringan', 'Spot sunrise & sunset']::text[]),
  (5, 'Desa Sade', 'Wisata Budaya', 'Lombok Tengah', 'Desa adat Sasak yang menampilkan rumah tradisional, kain tenun, dan budaya lokal.', 'Tempat belajar budaya Sasak dan melihat speciality lokal Lombok.', 0, 'Donasi / paket lokal', '08.00 - 17.00', 4.4, -8.8395, 116.2924, array['/images/desa_sade.jpeg', 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=70', 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=70']::text[], array['Guide lokal', 'Toko tenun', 'Pertunjukan budaya', 'Parkir']::text[]),
  (6, 'Warung Ayam Taliwang', 'Kuliner', 'Mataram', 'Kuliner khas Lombok dengan ayam bakar berbumbu kuat dan pilihan level pedas.', 'Speciality pedas lokal yang wajib diuji untuk food hunter.', 25000, 'Rp25.000 - Rp75.000', '10.00 - 22.00', 4.6, -8.5908, 116.1203, array['/images/ayam_taliwang.jpeg', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=70', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=70']::text[], array['Halal', 'Parkir', 'Level pedas custom', 'Buka malam']::text[]),
  (7, 'Nasi Balap Puyung', 'Kuliner', 'Mataram / Lombok Tengah', 'Nasi khas Lombok dengan lauk ayam suwir pedas dan bumbu gurih.', 'Cocok untuk pencarian makanan pedas, cepat, dan lokal banget.', 15000, 'Rp15.000 - Rp35.000', '08.00 - 21.00', 4.5, -8.7221, 116.2702, array['/images/nasi_puyung.jpeg', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=70', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=70']::text[], array['Halal', 'Murah meriah', 'Cepat saji', 'Bungkus tersedia']::text[]),
  (8, 'Kafe Ampenan Heritage', 'Kafe', 'Kota Tua Ampenan', 'Kafe bernuansa heritage di kawasan tua dekat pesisir Ampenan.', 'Cocok untuk nongkrong tenang, foto, dan eksplor suasana kota lama.', 25000, 'Rp25.000 - Rp75.000', '10.00 - 22.00', 4.2, -8.5679, 116.0729, array['/images/ampenan_heritage.jpeg', '/images/foto_ampenan.jpeg', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=70']::text[], array['WiFi', 'Colokan banyak', 'Indoor & outdoor', 'Spot foto vintage']::text[]),
  (9, 'Gili Trawangan', 'Pulau & Snorkeling', 'Lombok Utara', 'Pulau paling populer di Lombok: snorkeling, sepeda keliling pulau, dan kehidupan malam santai tanpa kendaraan bermotor.', 'Kombinasi langka: laut jernih untuk snorkeling siang, sunset swing sore, live music malam.', 50000, 'Boat mulai Rp50.000', '24 jam', 4.8, -8.3506, 116.0392, array['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (10, 'Air Terjun Sendang Gile', 'Wisata Alam', 'Senaru, Lombok Utara', 'Air terjun dua tingkat di kaki Rinjani dengan trek tangga yang mudah diikuti.', 'Air terjun paling mudah diakses di Senaru — cocok untuk pemanasan sebelum Tiu Kelep.', 20000, 'Rp20.000', '07.00 - 17.00', 4.6, -8.3055, 116.4043, array['https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (11, 'Bukit Selong', 'Wisata Alam', 'Sembalun, Lombok Timur', 'Bukit pendek dengan panorama petak sawah warna-warni khas Sembalun.', 'Naik 10 menit, dapat view yang biasa muncul di kalender — terbaik saat pagi berkabut.', 10000, 'Rp10.000', '06.00 - 18.00', 4.7, -8.3621, 116.5352, array['https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (12, 'Pantai Tanjung Aan', 'Wisata Pantai', 'Kuta, Lombok Tengah', 'Pantai pasir merica dengan air dangkal tenang dan ayunan foto ikonik.', 'Pasirnya bulat seperti merica — unik di dunia. Bukit Merese persis di sebelahnya.', 10000, 'Rp10.000 - Rp25.000', '06.00 - 18.30', 4.7, -8.9086, 116.3233, array['https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (13, 'Pink Beach (Tangsi)', 'Wisata Pantai', 'Lombok Timur', 'Pantai berpasir merah muda alami — satu dari sedikit di dunia.', 'Warna pink dari serpihan koral merah. Datang saat matahari tinggi agar warna maksimal.', 10000, 'Rp10.000', '07.00 - 17.00', 4.5, -8.8683, 116.5478, array['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (14, 'Gili Nanggu', 'Pulau & Snorkeling', 'Sekotong, Lombok Barat', 'Pulau kecil tenang di barat daya Lombok dengan terumbu dangkal penuh ikan.', 'Versi sepi dari Gili — snorkeling langsung dari pantai, serasa pulau pribadi.', 300000, 'Boat mulai Rp300.000/perahu', '07.00 - 17.00', 4.7, -8.7364, 115.9371, array['https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (15, 'Air Terjun Tiu Kelep', 'Wisata Alam', 'Senaru, Lombok Utara', 'Air terjun megah dengan kolam alami — trek 45 menit menembus hutan dan sungai.', 'Berdiri di bawah tirai airnya adalah pengalaman paling menyegarkan di Lombok.', 20000, 'Rp20.000 + guide lokal', '07.00 - 16.30', 4.8, -8.3033, 116.4098, array['https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (16, 'Sembalun Lawang', 'Wisata Alam', 'Kaki Rinjani, Lombok Timur', 'Desa di lembah kaki Rinjani: udara sejuk, kebun stroberi, dan titik awal pendakian.', 'Suasana pegunungan 1.100 mdpl — sisi Lombok yang jarang dilihat wisatawan pantai.', 10000, 'Gratis - Rp10.000', '24 jam', 4.6, -8.3482, 116.5257, array['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (17, 'Kota Tua Ampenan', 'Wisata Budaya', 'Ampenan, Mataram', 'Kawasan pelabuhan lama dengan bangunan art-deco, kampung multietnis, dan sunset pantai.', 'Lapisan sejarah Tionghoa-Arab-Melayu dalam satu kawasan yang fotogenik.', 0, 'Gratis', '24 jam (terbaik sore)', 4.4, -8.5672, 116.0721, array['/images/foto_ampenan.jpeg']::text[], array['Parkir', 'Toilet']::text[]),
  (18, 'Pantai Kuta Mandalika', 'Wisata Pantai', 'Kuta, Lombok Tengah', 'Pantai utama kawasan Mandalika dengan fasilitas lengkap dan akses mudah.', 'Basis terbaik untuk eksplor pantai selatan — dekat sirkuit MotoGP Mandalika.', 10000, 'Gratis - Rp10.000', '06.00 - 19.00', 4.5, -8.8945, 116.2833, array['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (19, 'Desa Tenun Sukarara', 'Wisata Budaya', 'Lombok Tengah', 'Sentra tenun songket Sasak — lihat proses menenun dan coba pakaian adat.', 'Beli kain langsung dari penenunnya, plus foto berbusana adat Sasak gratis.', 0, 'Gratis (donasi)', '08.00 - 17.00', 4.5, -8.7152, 116.2531, array['https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]),
  (20, 'Sate Rembiga Ibu Sinnaseh', 'Kuliner', 'Rembiga, Mataram', 'Sate sapi manis-pedas legendaris khas kampung Rembiga sejak puluhan tahun.', 'Bumbu manis-pedas yang meresap sampai serat daging — banyak yang bilang sate terenak di Lombok.', 20000, 'Rp20.000 - Rp50.000', '09.00 - 22.00', 4.7, -8.5754, 116.1052, array['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=70']::text[], array['Parkir', 'Toilet']::text[]);

-- Spot tags
insert into public.spot_tags (spot_id, tag_id)
select s.id, t.id from (values
  (1, 'landmark'),
  (1, 'aesthetic'),
  (1, 'budaya'),
  (1, 'keluarga'),
  (1, 'murah'),
  (1, 'foto-foto'),
  (2, 'healing'),
  (2, 'tenang'),
  (2, 'keluarga'),
  (2, 'murah'),
  (2, 'jalan santai'),
  (2, 'kota'),
  (3, 'sunset'),
  (3, 'romantis'),
  (3, 'pantai'),
  (3, 'keluarga'),
  (3, 'foto-foto'),
  (3, 'populer'),
  (4, 'healing'),
  (4, 'sunset'),
  (4, 'aesthetic'),
  (4, 'adventurous'),
  (4, 'foto-foto'),
  (4, 'nature'),
  (5, 'budaya'),
  (5, 'lokal banget'),
  (5, 'keluarga'),
  (5, 'aesthetic'),
  (5, 'belajar budaya'),
  (5, 'hidden gem'),
  (6, 'pedas'),
  (6, 'kuliner lokal'),
  (6, 'halal'),
  (6, 'food hunter'),
  (6, 'populer'),
  (6, 'malam'),
  (7, 'pedas'),
  (7, 'murah'),
  (7, 'kuliner lokal'),
  (7, 'halal'),
  (7, 'cepat'),
  (7, 'hidden gem'),
  (8, 'aesthetic'),
  (8, 'cozy'),
  (8, 'tenang'),
  (8, 'hidden gem'),
  (8, 'nongkrong'),
  (8, 'foto-foto'),
  (9, 'snorkeling'),
  (9, 'pantai'),
  (9, 'sunset'),
  (9, 'populer'),
  (9, 'adventurous'),
  (9, 'romantis'),
  (10, 'air terjun'),
  (10, 'nature'),
  (10, 'healing'),
  (10, 'keluarga'),
  (10, 'foto-foto'),
  (11, 'aesthetic'),
  (11, 'foto-foto'),
  (11, 'hidden gem'),
  (11, 'nature'),
  (11, 'murah'),
  (11, 'tenang'),
  (12, 'pantai'),
  (12, 'keluarga'),
  (12, 'aesthetic'),
  (12, 'foto-foto'),
  (12, 'populer'),
  (13, 'pantai'),
  (13, 'hidden gem'),
  (13, 'aesthetic'),
  (13, 'foto-foto'),
  (13, 'adventurous'),
  (14, 'snorkeling'),
  (14, 'hidden gem'),
  (14, 'tenang'),
  (14, 'romantis'),
  (14, 'healing'),
  (15, 'air terjun'),
  (15, 'adventurous'),
  (15, 'nature'),
  (15, 'healing'),
  (15, 'hidden gem'),
  (16, 'nature'),
  (16, 'tenang'),
  (16, 'healing'),
  (16, 'adventurous'),
  (16, 'keluarga'),
  (17, 'budaya'),
  (17, 'aesthetic'),
  (17, 'foto-foto'),
  (17, 'sunset'),
  (17, 'murah'),
  (17, 'hidden gem'),
  (18, 'pantai'),
  (18, 'keluarga'),
  (18, 'populer'),
  (18, 'sunset'),
  (18, 'murah'),
  (19, 'budaya'),
  (19, 'belajar budaya'),
  (19, 'lokal banget'),
  (19, 'keluarga'),
  (19, 'foto-foto'),
  (20, 'kuliner lokal'),
  (20, 'pedas'),
  (20, 'halal'),
  (20, 'populer'),
  (20, 'food hunter'),
  (20, 'murah')
) as v(spot_id, tag_name)
join public.spots s on s.id = v.spot_id
join public.tags t on t.name = v.tag_name;

-- Partners
insert into public.partners (name, base, since, descr, spesialis) values
  ('Lombok Tenang Tour', 'Senggigi, Lombok Barat', '2019', 'Spesialis slow travel dan retreat. Tim kecil yang percaya liburan terbaik adalah yang tidak terburu-buru.', 'Healing & retreat'),
  ('Rasa Lombok Trip', 'Mataram', '2021', 'Didirikan food blogger lokal — tahu semua warung legendaris yang tidak muncul di Google Maps.', 'Kuliner'),
  ('Merese Adventure', 'Kuta, Lombok Tengah', '2018', 'Operator trekking dan camping berlisensi dengan guide bersertifikat serta peralatan lengkap.', 'Trekking & outdoor'),
  ('Ampenan Frame', 'Ampenan, Mataram', '2022', 'Kolektif fotografer muda Lombok — tur mereka setengah jalan-jalan, setengah photoshoot profesional.', 'Foto & konten'),
  ('Senggigi Couple', 'Senggigi, Lombok Barat', '2020', 'Spesialis momen romantis: dinner privat, lamaran, honeymoon. Detail kecil adalah keahlian mereka.', 'Romantis & privat'),
  ('Lombok Keluarga', 'Mataram', '2017', 'Operator tur keluarga paling berpengalaman — itinerary teruji untuk balita sampai kakek-nenek.', 'Keluarga');

-- Packages
insert into public.packages (partner_id, name, persona, descr, durasi, price, include)
select p.id, v.name, v.persona, v.descr, v.durasi, v.price, v.include from (values
  ('Lombok Tenang Tour', 'Slow Trip Healing 3 Hari', 'Sang Penenang', 'Retreat santai: taman kota, sunset Senggigi, dan spot tenang jauh dari keramaian. Ritme perjalanan dibuat pelan — banyak waktu kosong untuk sekadar duduk dan bernapas.', '3 hari 2 malam', 1250000, array['Penginapan tenang 2 malam', 'Transport & sopir lokal', 'Sesi yoga pantai saat sunrise', 'Makan 3x sehari (menu sehat)']::text[]),
  ('Rasa Lombok Trip', 'Food Trail Lombok', 'Pemburu Rasa', 'Ayam Taliwang legendaris, Nasi Balap Puyung asli, dan tur pasar malam dalam satu hari penuh. Level pedas bisa disesuaikan — dari penasaran sampai penantang.', '1 hari (08.00–21.00)', 450000, array['Transport keliling seharian', '5+ kuliner legendaris (sudah termasuk)', 'Guide food hunter lokal', 'Air mineral & obat sakit perut 😄']::text[]),
  ('Merese Adventure', 'Trekking Bukit Merese & Sunrise', 'Sang Petualang', 'Camping di kaki bukit, summit dini hari untuk sunrise di atas savana Merese, lanjut island hopping ringan ke gili sekitar Kuta Lombok.', '2 hari 1 malam', 650000, array['Peralatan camping lengkap', 'Guide trekking bersertifikat', 'Island hopping ringan', 'Dokumentasi foto & drone']::text[]),
  ('Ampenan Frame', 'Photo Spot Tour Kota Tua', 'Pemburu Estetik', 'Rute terkurasi untuk konten: Desa Sade, Kota Tua Ampenan, Kafe Ampenan Heritage, dan beberapa hidden gem yang belum ramai di sosmed.', '1 hari (07.00–18.00)', 400000, array['Guide sekaligus fotografer', '20 foto teredit siap posting', 'Tiket masuk semua spot', 'Rekomendasi golden hour terbaik']::text[]),
  ('Senggigi Couple', 'Sunset Dinner Romantis', 'Sang Romantis', 'Private beach dengan setup candlelight, seafood dinner segar, dan spa pasangan. Cocok untuk anniversary, lamaran, atau sekadar merayakan berdua.', '1 malam (16.00–21.00)', 900000, array['Setup private beach & dekorasi', 'Candlelight seafood dinner', 'Spa pasangan 60 menit', 'Dokumentasi momen']::text[]),
  ('Lombok Keluarga', 'Family Explore 4 Hari', 'Penjelajah Keluarga', 'Itinerary ramah anak: edukasi budaya di Desa Sade, pantai landai yang aman, dan aktivitas seru untuk semua umur. Tempo santai, banyak jeda istirahat.', '4 hari 3 malam', 2100000, array['Hotel ramah keluarga 3 malam', 'Aktivitas edukasi anak', 'Transport nyaman (car seat tersedia)', 'Asuransi perjalanan keluarga']::text[])
) as v(partner_name, name, persona, descr, durasi, price, include)
join public.partners p on p.name = v.partner_name;

-- Products
insert into public.products (name, descr, price, kategori, image) values
  ('Tumbler MoodTrip', 'Botol minum 750ml, tahan dingin 12 jam', 89000, 'gear', 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=70'),
  ('Dry Bag 10L', 'Anti air — aman untuk island hopping', 120000, 'gear', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=70'),
  ('Daypack Lipat 20L', 'Ringan, bisa dilipat sekepal tangan', 135000, 'gear', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=70'),
  ('Tripod Mini HP', 'Buat konten sunset tanpa minta tolong', 95000, 'gear', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=600&q=70'),
  ('Power Bank 10.000mAh', 'Dua port, fast charging', 180000, 'gear', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=70'),
  ('Topi Pantai', 'Anyaman ringan, siap golden hour', 75000, 'gear', 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=600&q=70'),
  ('Kain Tenun Sasak', 'Tenun ikat asli Desa Sukarara', 250000, 'khas_lombok', 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=70'),
  ('Scarf Tenun Sasak', 'Motif tradisional, cocok buat OOTD', 150000, 'khas_lombok', 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=70'),
  ('Gelang Mutiara Sekarbela', 'Mutiara asli sentra Sekarbela, Mataram', 175000, 'khas_lombok', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=70'),
  ('Anyaman Ketak Lombok', 'Tas/keranjang anyaman tangan khas Lombok', 95000, 'khas_lombok', 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=600&q=70'),
  ('Sambal Kit Lombok', 'Paket sambal khas — level pedas pilihan', 65000, 'khas_lombok', 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=70'),
  ('Kopi Sembalun', 'Robusta kaki Rinjani, sangrai medium', 55000, 'khas_lombok', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=70');

-- Restos
insert into public.restos (name, location, hours, about, image, lat, lng, is_open) values
  ('Warung Ayam Taliwang', 'Mataram', '10.00 - 22.00', 'Warung legendaris dengan ayam kampung bakar bumbu taliwang asli. Level pedas bisa diminta dari ringan sampai ekstrem.', '/images/ayam_taliwang.jpeg', -8.5908, 116.1203, true),
  ('Nasi Balap Puyung', 'Lombok Tengah', '08.00 - 21.00', 'Nasi balap khas Desa Puyung: ayam suwir pedas, kering kentang, dan bumbu gurih yang bikin nambah.', '/images/nasi_puyung.jpeg', -8.7221, 116.2702, true),
  ('Kafe Ampenan Heritage', 'Kota Tua Ampenan', '10.00 - 22.00', 'Kafe bernuansa kolonial di kota tua Ampenan. Kopi Lombok single origin dan spot foto vintage di setiap sudut.', '/images/ampenan_heritage.jpeg', -8.5679, 116.0729, false);

-- Menu items
insert into public.menu_items (resto_id, name, price, ready)
select r.id, v.name, v.price, v.ready from (values
  ('Warung Ayam Taliwang', 'Ayam Taliwang (pedas)', 45000, true),
  ('Warung Ayam Taliwang', 'Plecing Kangkung', 15000, true),
  ('Warung Ayam Taliwang', 'Beberuk Terong', 12000, false),
  ('Warung Ayam Taliwang', 'Es Kelapa Muda', 10000, true),
  ('Nasi Balap Puyung', 'Nasi Balap Komplit', 25000, true),
  ('Nasi Balap Puyung', 'Ayam Suwir Pedas', 18000, true),
  ('Nasi Balap Puyung', 'Kering Kentang', 10000, false),
  ('Kafe Ampenan Heritage', 'Kopi Lombok', 22000, true),
  ('Kafe Ampenan Heritage', 'Croissant', 28000, true),
  ('Kafe Ampenan Heritage', 'Matcha Latte', 30000, false)
) as v(resto_name, name, price, ready)
join public.restos r on r.name = v.resto_name;
